### ISSUE TITLE
Issue test 1

### ISSUE THREAD

**Issue by mumblespolecat** [2030428/VR-World-The-Maze#1]
Hi Seb.  My isssue is that your dungeon is much better than my farm !  Good job :)  Matthew

**Comment by virtualosus** [comment]
Hahaha! Nah, I think I over-complicated it for myself, but I got an idea in my head at the beginning, and then before I knew it I was in too deep.... if you know what I mean! I spent far too much time trying to sort out issues I had made for myself in the end. I'm happy with how it came out, but there were no extra marks for self-punishment!!

Yours looks great btw, I wish I had stuck with the open plan concept. Plus yours had a clear concept with education for kids, mine was just a bit of gamey-fun... Hopefully we both ticked all the boxes properly!

Speak soon
________________________________
